CREATE TABLE IF NOT EXISTS ai_performance_scores (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    intern_id BIGINT NOT NULL,
    computed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    week_number INT NOT NULL,
    attendance_score DECIMAL(6,2) NOT NULL,
    task_completion_score DECIMAL(6,2) NOT NULL,
    work_quality_score DECIMAL(6,2) NOT NULL,
    technical_skills_score DECIMAL(6,2) NOT NULL,
    conduct_engagement_score DECIMAL(6,2) NOT NULL,
    final_score DECIMAL(6,2) NOT NULL,
    grade VARCHAR(32) NOT NULL,
    prediction VARCHAR(32) NOT NULL,
    prediction_confidence DECIMAL(6,4) NOT NULL,
    insights JSON NULL,
    recommendations JSON NULL,
    skill_gaps JSON NULL,
    score_trend VARCHAR(32) NULL,
    previous_score DECIMAL(6,2) NULL,
    score_change DECIMAL(6,2) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_ai_scores_intern (intern_id),
    KEY idx_ai_scores_week (week_number),
    KEY idx_ai_scores_computed_at (computed_at),
    CONSTRAINT fk_ai_scores_intern FOREIGN KEY (intern_id) REFERENCES interns(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
