CREATE TABLE IF NOT EXISTS ai_alerts (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    intern_id BIGINT NOT NULL,
    supervisor_id BIGINT NULL,
    alert_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    triggered_value DECIMAL(10,2) NULL,
    threshold_value DECIMAL(10,2) NULL,
    is_read TINYINT(1) NOT NULL DEFAULT 0,
    is_resolved TINYINT(1) NOT NULL DEFAULT 0,
    resolved_at DATETIME(6) NULL,
    resolved_by BIGINT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    KEY idx_ai_alerts_intern (intern_id),
    KEY idx_ai_alerts_supervisor (supervisor_id),
    KEY idx_ai_alerts_type (alert_type),
    KEY idx_ai_alerts_severity (severity),
    KEY idx_ai_alerts_read_resolved (is_read, is_resolved),
    CONSTRAINT fk_ai_alerts_intern FOREIGN KEY (intern_id) REFERENCES interns(id),
    CONSTRAINT fk_ai_alerts_supervisor FOREIGN KEY (supervisor_id) REFERENCES users(id),
    CONSTRAINT fk_ai_alerts_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
